apiVersion: v1
kind: Service
metadata:
  name: note-pinner-backend
  labels:
    app: note-pinner-backend
spec:
  type: ClusterIP
  selector:
    app: note-pinner-backend
  ports:
    - name: http
      port: 4000
      targetPort: 4000

