services:
  backend:
    build:
      context: /home/wala/Downloads/mini-devops-app/backend
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20.18.0
    environment:
      - PORT=4000
    ports:
      - '4000:4000'
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:4000/healthz']
      interval: 10s
      timeout: 3s
      retries: 3

  frontend:
    build:
      context: /home/wala/Downloads/mini-devops-app/frontend
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20.18.0
        VITE_API_URL: /api
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - '3000:80'

