apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
  labels:
    app.kubernetes.io/component: backend
    {{- include "note-pinner.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "note-pinner.name" . }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http

