apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.service.name }}
  labels:
    {{- include "note-pinner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "note-pinner.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "note-pinner.name" . }}
      {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: backend
          image: {{ include "note-pinner.fullImageName" (dict "Values" .Values "image" .Values.backend.image) }}
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "{{ .Values.backend.service.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.livenessProbe.path }}
              port: {{ .Values.backend.livenessProbe.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.readinessProbe.path }}
              port: {{ .Values.backend.readinessProbe.port }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}

