apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-pinner-frontend
  labels:
    app: note-pinner-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: note-pinner-frontend
  template:
    metadata:
      labels:
        app: note-pinner-frontend
    spec:
      containers:
        - name: frontend
          image: wala19/mini-devops-app-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: note-pinner-frontend-config
                  key: VITE_API_URL
          volumeMounts:
            - name: frontend-nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: frontend-nginx-config
          configMap:
            name: note-pinner-frontend-config
            items:
              - key: default.conf
                path: default.conf

