apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: note-pinner-frontend
  labels:
    app: note-pinner-frontend
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
    - host: note-pinner.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: note-pinner-frontend
                port:
                  number: 80

